
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.CSS;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int rgb = 20;
  public static final int borderColor = 12;
  public static final int cadena = 22;
  public static final int hexadecimal = 25;
  public static final int fontColor = 17;
  public static final int fontSize = 16;
  public static final int coma = 9;
  public static final int numero = 21;
  public static final int comentarioMultiLinea = 24;
  public static final int comentarioLinea = 23;
  public static final int punto = 5;
  public static final int llaveC = 8;
  public static final int EOF = 0;
  public static final int font = 15;
  public static final int llaveA = 7;
  public static final int width = 19;
  public static final int border = 11;
  public static final int hight = 18;
  public static final int error = 1;
  public static final int align = 14;
  public static final int background = 10;
  public static final int parentesisC = 3;
  public static final int dosPuntos = 6;
  public static final int puntoComa = 4;
  public static final int parentesisA = 2;
  public static final int borderWidth = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "parentesisA",
  "parentesisC",
  "puntoComa",
  "punto",
  "dosPuntos",
  "llaveA",
  "llaveC",
  "coma",
  "background",
  "border",
  "borderColor",
  "borderWidth",
  "align",
  "font",
  "fontSize",
  "fontColor",
  "hight",
  "width",
  "rgb",
  "numero",
  "cadena",
  "comentarioLinea",
  "comentarioMultiLinea",
  "hexadecimal"
  };
}

